---
apiVersion: v1
kind: Service
metadata:
  name: lightspeed-mcp-external
  namespace: openshift-lightspeed
  labels:
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/part-of: openshift-lightspeed
spec:
  selector:
    app: openshift-mcp-server
    app.kubernetes.io/component: openshift-mcp-server
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
