---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacm-policies
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: all-clusters
  namespace: rhacm-policies
spec:
  clusterSet: all-clusters
