---
apiVersion: v1
kind: Namespace
metadata:
  name: standard-cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: standard-cluster-install-config
  namespace: standard-cluster
type: Opaque
stringData:
  install-config.yaml: |
    apiVersion: v1
    metadata:
      name: standard-cluster
    baseDomain: <YOUR_BASE_DOMAIN>
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      replicas: 1
      platform:
        aws:
          type: m6i.2xlarge
    compute:
    - architecture: amd64
      hyperthreading: Enabled
      name: worker
      replicas: 0
      platform:
        aws:
          type: m6i.2xlarge
    networking:
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.0.0.0/16
      networkType: OVNKubernetes
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      aws:
        region: us-east-2
    pullSecret: ""
    sshKey: "<YOUR_SSH_PUBLIC_KEY>"
---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: standard-cluster
  namespace: standard-cluster
  labels:
    cloud: AWS
    vendor: OpenShift
spec:
  baseDomain: <YOUR_BASE_DOMAIN>
  clusterName: standard-cluster
  installAttemptsLimit: 1
  installed: false
  platform:
    aws:
      credentialsSecretRef:
        name: aws-credentials
      region: us-east-2
  provisioning:
    installConfigSecretRef:
      name: standard-cluster-install-config
    imageSetRef:
      name: img4.20.16-multi-appsub
  pullSecretRef:
    name: pull-secret
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: standard-cluster
  labels:
    name: standard-cluster
    cloud: Amazon
    vendor: OpenShift
    environment: dev
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: standard-cluster
  namespace: standard-cluster
spec:
  clusterName: standard-cluster
  clusterNamespace: standard-cluster
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
