apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: httpd
          image: registry.access.redhat.com/ubi9/httpd-24:latest
          ports:
            - containerPort: 8080
              name: webserver
          volumeMounts:
            - mountPath: /var/www/html/application.html
              name: application-content
              subPath: application.html
      volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: application.html
              path: application.html
            name: application-content
          name: application-content
